apiVersion: apps/v1 
kind: Deployment
metadata:
  name:  simple-deployment
  labels:
    name:  simple-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
     name: simple-deployment 
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: simple-deployment 
    spec:
      containers:
      - image: jmalloc/echo-server
        name:  echo-server
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  PORT
          value:  "8080"       
        ports:
        - containerPort:  8080
          name:  http